name: Golang Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.10'
      - run: make tests
